# -*- coding: utf-8 -*-
"""Data_Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbShK8hMQVDhQfid2IDvdb_fhs668rP4

<a href="https://colab.research.google.com/github/abhikr1302/Data_Extraction/blob/main/Data_Extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Extraction and NLP**

## **Objective**
The objective of this assignment is to extract textual data articles from the given URL and perform text analysis to compute variables that are explained below.

## **Importing The Libraries**
"""

!pip install fake_useragent

from bs4 import BeautifulSoup
import requests
import pandas as pd
import re
import requests.exceptions
from fake_useragent import UserAgent
from datetime import datetime
import nltk
import string
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
nltk.download('punkt')
import glob
import os

#importing the drive

from google.colab import drive
drive.mount('/content/drive')

"""## **Data Study**"""

#Loading File

df=pd.read_excel('/content/drive/MyDrive/20211030 Test Assignment/Input.xlsx')

df.head()

df.info()

df['URL'][0]

"""## **Data Manipulation**"""

# Function to find if there is any error in URL
urls = df['URL'].tolist()
status = []

## initializing the UserAgent object
user_agent = UserAgent()

for url in urls:
    try:
        r = requests.get(url,headers={"user-agent": user_agent.chrome})
        r.raise_for_status()
    except (requests.exceptions.ConnectionError, requests.exceptions.Timeout):
        status.append("Down")
    except requests.exceptions.HTTPError:
        status.append("HTTP error")
    else:
        status.append("All good")
df['status'] = status

df.loc[df['status']=='HTTP error']

"""We find that three URLs are not working."""

# removing rows that have HTTP error
df = df.loc[df['status']=='All good']
df

# Function to find date of the article when it is uploaded
urls = df['URL'].tolist()
Date = []

## initializing the UserAgent object
user_agent = UserAgent()

#scrape elements
for url in urls:
  response = requests.get(url, headers={"user-agent": user_agent.chrome})
  soup = BeautifulSoup(response.content, "html.parser")

  ## Then parse the HTML, extract title and article
  date = soup.find(attrs={'class':'entry-date updated td-module-date'}).text
  Date.append(date)

df['date'] = Date

df

"""## **Data Extraction**

### **Function to extract Title and Text from Article monthwise**
"""

# Converting data into datetime format
df['date']= pd.to_datetime(df['date'])
df['date']

# Using pandas.DatetimeIndex() to extract month and year
df['year'] = pd.DatetimeIndex(df['date']).year
df['month'] = pd.DatetimeIndex(df['date']).month

"""### **January**"""

jan_df = df.loc[df['month']==1]

#Function to extract Title and text from the article published in January
## create an array with URLs
urls = jan_df['URL']

## initializing the UserAgent object
user_agent = UserAgent()

# defining empty list for title and text
title_all = []
text_all = []

#scrape elements
for url in urls:
  response = requests.get(url, headers={"user-agent": user_agent.chrome})
  soup = BeautifulSoup(response.content, "html.parser")

  ## Then parse the HTML, extract title and article
  jan_title = soup.find(attrs={'class':'td-post-title'}).text.replace('\n','')
  jan_title = (re.findall('Think(.*)January', jan_title))
  jan_text = soup.find(attrs={'class':'td-post-content'}).text.replace('\n','')

  if jan_title == []:
    print("Title could not be found")
    continue
  else:
    print(f"Title of the article is : {jan_title} \nText of the article is : {jan_text}")
# get the domain as the file name
  domain = " ".join(jan_title)
  description = jan_text
  filename = response.url.replace("/",'') + '.txt'
  with open("/content/drive/MyDrive/20211030 Test Assignment/output/" + filename, 'w') as f:
      f.write(domain +'\n' + description)

# appending all the title and text in a list
  domain = " ".join(jan_title)
  description = jan_text
  title_all.append(domain)
  text_all.append(description)

# adding title and text to the dataframe
jan_df.insert(2,'Title', title_all)
jan_df.insert(3,'Text', text_all)
jan_df

"""### **February**"""

feb_df = df.loc[df['month']==2]

#Function to extract Title and text from the article published in February
## create an array with URLs
urls = feb_df['URL']

## initializing the UserAgent object
user_agent = UserAgent()

# defining empty list for title and text
title_all = []
text_all = []

#scrape elements
for url in urls:
  response = requests.get(url, headers={"user-agent": user_agent.chrome})
  soup = BeautifulSoup(response.content, "html.parser")

  ## Then parse the HTML, extract title and article
  feb_title = soup.find(attrs={'class':'td-post-title'}).text.replace('\n','')
  feb_title = (re.findall('Think(.*)February', feb_title))
  feb_text = soup.find(attrs={'class':'td-post-content'}).text.replace('\n','')

  if feb_title == []:
    print("Title could not be found")
    continue
  else:
    print(f"Title of the article is : {feb_title} \nText of the article is : {feb_text}")
# get the domain as the file name
  domain = " ".join(feb_title)
  description = feb_text
  filename = response.url.replace("/",'') + '.txt'
  with open("/content/drive/MyDrive/20211030 Test Assignment/output/" + filename, 'w') as f:
      f.write(domain +'\n' + description)

  # appending all the title and text in a list
  domain = " ".join(feb_title)
  description = feb_text
  title_all.append(domain)
  text_all.append(description)

# adding title and text to the dataframe
feb_df.insert(2,'Title', title_all)
feb_df.insert(3,'Text', text_all)
feb_df

"""### **March**"""

mar_df = df.loc[df['month']==3]

#Function to extract Title and text from the article published in March
## create an array with URLs
urls = mar_df['URL']

## initializing the UserAgent object
user_agent = UserAgent()

# defining empty list for title and text
title_all = []
text_all = []

#scrape elements
for url in urls:
  response = requests.get(url, headers={"user-agent": user_agent.chrome})
  soup = BeautifulSoup(response.content, "html.parser")

  ## Then parse the HTML, extract title and article
  mar_title = soup.find(attrs={'class':'td-post-title'}).text.replace('\n','')
  mar_title = (re.findall('Think(.*)March', mar_title))
  mar_text = soup.find(attrs={'class':'td-post-content'}).text.replace('\n','')

  if mar_title == []:
    print("Title could not be found")
    continue
  else:
    print(f"Title of the article is : {mar_title} \nText of the article is : {mar_text}")

  # get the domain as the file name
  domain = " ".join(mar_title)
  description = mar_text
  filename = response.url.replace("/",'') + '.txt'
  with open("/content/drive/MyDrive/20211030 Test Assignment/output/" + filename, 'w') as f:
      f.write(domain +'\n' + description)

  # appending all the title and text in a list
  domain = " ".join(mar_title)
  description = mar_text
  title_all.append(domain)
  text_all.append(description)

"""**Title of one Article was not found. Lets find it out now**"""

mar_df

"""**We can see that Title of URL in index 98 can't be extracted. Lets find it out now.**"""

# Finding the title of article which was not found earlier
urls = 'https://insights.blackcoffer.com/should-people-wear-fabric-gloves-seeking-evidence-regarding-the-differential-transfer-of-covid-19-or-coronaviruses-generally-between-surfaces/'

## initializing the UserAgent object
user_agent = UserAgent()

#scrape elements
response = requests.get(urls, headers={"user-agent": user_agent.chrome})
soup = BeautifulSoup(response.content, "html.parser")

## Then parse the HTML, extract title and article
mar_title = soup.find(attrs={'class':'td-post-title'}).text.replace('\n','')
mar_title = (re.findall('Sciences(.*)March', mar_title))
mar_text = soup.find(attrs={'class':'td-post-content'}).text.replace('\n','')

print(f"Title of the article is : {mar_title} \nText of the article is : {mar_text}")

# get the domain as the file name
domain = " ".join(mar_title)
description = mar_text
filename = response.url.replace("/",'') + '.txt'
with open("/content/drive/MyDrive/20211030 Test Assignment/output/" + filename, 'w') as f:
  f.write(domain +'\n' + description)

# appending all the title and text in a list
domain = " ".join(mar_title)
description = mar_text
title_all.append(domain)
text_all.append(description)

title_all

# rearranging dataframe
mar_df_re = mar_df.reindex([23,24,25,97,99,100,101,98])
mar_df_re

# adding title and text to the dataframe
mar_df_re.insert(2,'Title', title_all)
mar_df_re.insert(3,'Text', text_all)
mar_df_re

"""### **April**"""

apr_df = df.loc[df['month']==4]

#Function to extract Title and text from the article published in April
## create an array with URLs
urls = apr_df['URL']

## initializing the UserAgent object
user_agent = UserAgent()

# defining empty list for title and text
title_all = []
text_all = []

#scrape elements
for url in urls:
  response = requests.get(url, headers={"user-agent": user_agent.chrome})
  soup = BeautifulSoup(response.content, "html.parser")

  ## Then parse the HTML, extract title and article
  apr_title = soup.find(attrs={'class':'td-post-title'}).text.replace('\n','')
  apr_title = (re.findall('Think(.*)April', apr_title))
  apr_text = soup.find(attrs={'class':'td-post-content'}).text.replace('\n','')
  if apr_title == []:
    print("Title could not be found")
    continue
  else:
    print(f"Title of the article is : {apr_title} \nText of the article is : {apr_text}")
# get the domain as the file name
  domain = " ".join(apr_title)
  description = apr_text
  filename = response.url.replace("/",'') + '.txt'
  with open("/content/drive/MyDrive/20211030 Test Assignment/output/" + filename, 'w') as f:
      f.write(domain +'\n' + description)
  # appending all the title and text in a list
  domain = " ".join(apr_title)
  description = apr_text
  title_all.append(domain)
  text_all.append(description)

apr_df

"""**We can see that Title of URL in index 102,103,105 can't be extracted. Lets find it out now**"""

# Left over articles
urls = 'https://insights.blackcoffer.com/industrial-revolution-4-0-pros-and-cons/'

## initializing the UserAgent object
user_agent = UserAgent()

#scrape elements
response = requests.get(urls, headers={"user-agent": user_agent.chrome})
soup = BeautifulSoup(response.content, "html.parser")

## Then parse the HTML, extract title and article
apr_title = soup.find(attrs={'class':'td-post-title'}).text.replace('\n','')
apr_title = (re.findall('Technology(.*)April', apr_title))
apr_text = soup.find(attrs={'class':'td-post-content'}).text.replace('\n','')

print(f"Title of the article is : {apr_title} \nText of the article is : {apr_text}")
# get the domain as the file name
domain = " ".join(apr_title)
description = apr_text
filename = response.url.replace("/",'') + '.txt'
with open("/content/drive/MyDrive/20211030 Test Assignment/output/" + filename, 'w') as f:
  f.write(domain +'\n' + description)

# appending all the title and text in a list
domain = " ".join(apr_title)
description = apr_text
title_all.append(domain)
text_all.append(description)

# Left over articles
urls = 'https://insights.blackcoffer.com/impact-of-covid-19-coronavirus-on-the-indian-economy/'

## initializing the UserAgent object
user_agent = UserAgent()

#scrape elements
response = requests.get(urls, headers={"user-agent": user_agent.chrome})
soup = BeautifulSoup(response.content, "html.parser")

## Then parse the HTML, extract title and article
apr_title = soup.find(attrs={'class':'td-post-title'}).text.replace('\n','')
apr_title = (re.findall('Pharmaceutical(.*)April', apr_title))
apr_text = soup.find(attrs={'class':'td-post-content'}).text.replace('\n','')

print(f"Title of the article is : {apr_title} \nText of the article is : {apr_text}")
# get the domain as the file name
domain = " ".join(apr_title)
description = apr_text
filename = response.url.replace("/",'') + '.txt'
with open("/content/drive/MyDrive/20211030 Test Assignment/output/" + filename, 'w') as f:
  f.write(domain +'\n' + description)

# appending all the title and text in a list
domain = " ".join(apr_title)
description = apr_text
title_all.append(domain)
text_all.append(description)

# Left over articles
urls = 'https://insights.blackcoffer.com/impact-of-covid-19coronavirus-on-the-indian-economy/'

## initializing the UserAgent object
user_agent = UserAgent()

#scrape elements
response = requests.get(urls, headers={"user-agent": user_agent.chrome})
soup = BeautifulSoup(response.content, "html.parser")

## Then parse the HTML, extract title and article
apr_title = soup.find(attrs={'class':'td-post-title'}).text.replace('\n','')
apr_title = (re.findall('Healthcare(.*)April', apr_title))
apr_text = soup.find(attrs={'class':'td-post-content'}).text.replace('\n','')

print(f"Title of the article is : {apr_title} \nText of the article is : {apr_text}")
# get the domain as the file name
domain = " ".join(apr_title)
description = apr_text
filename = response.url.replace("/",'') + '.txt'
with open("/content/drive/MyDrive/20211030 Test Assignment/output/" + filename, 'w') as f:
  f.write(domain +'\n' + description)

# appending all the title and text in a list
domain = " ".join(apr_title)
description = apr_text
title_all.append(domain)
text_all.append(description)

# rearranging dataframe
apr_df_re = apr_df.reindex([21,22,71,72,73,74,75,76,77,78,79,83,84,85,86,87,88,89,90,91,92,93,94,104,106,102,103,105])
apr_df_re

# adding title and text to the dataframe
apr_df_re.insert(2,'Title', title_all)
apr_df_re.insert(3,'Text', text_all)
apr_df_re

"""### **May**"""

may_df = df.loc[df['month']==5]

#Function to extract Title and text from the article published in May
## create an array with URLs
urls = may_df['URL']

## initializing the UserAgent object
user_agent = UserAgent()

# defining empty list for title and text
title_all = []
text_all = []

#scrape elements
for url in urls:
  response = requests.get(url, headers={"user-agent": user_agent.chrome})
  soup = BeautifulSoup(response.content, "html.parser")

  ## Then parse the HTML, extract title and article
  may_title = soup.find(attrs={'class':'td-post-title'}).text.replace('\n','')
  may_title = (re.findall('Think(.*)May', may_title))
  may_text = soup.find(attrs={'class':'td-post-content'}).text.replace('\n','')
  if may_title == []:
    print("Title could not be found")
    continue
  else:
    print(f"Title of the article is : {may_title} \nText of the article is : {may_text}")

  # get the domain as the file name
  domain = " ".join(may_title)
  description = may_text
  filename = response.url.replace("/",'') + '.txt'
  with open("/content/drive/MyDrive/20211030 Test Assignment/output/" + filename, 'w') as f:
      f.write(domain +'\n' + description)

  # appending all the title and text in a list
  domain = " ".join(may_title)
  description = may_text
  title_all.append(domain)
  text_all.append(description)

# adding title and text to the dataframe
may_df.insert(2,'Title', title_all)
may_df.insert(3,'Text', text_all)
may_df

"""### **June**"""

june_df = df.loc[df['month']==6]

#Function to extract Title and text from the article published in June
## create an array with URLs
urls = june_df['URL']

## initializing the UserAgent object
user_agent = UserAgent()

# defining empty list for title and text
title_all = []
text_all = []

#scrape elements
for url in urls:
  response = requests.get(url, headers={"user-agent": user_agent.chrome})
  soup = BeautifulSoup(response.content, "html.parser")

  ## Then parse the HTML, extract title and article
  june_title = soup.find(attrs={'class':'td-post-title'}).text.replace('\n','')
  june_title = (re.findall('Think(.*)June', june_title))
  june_text = soup.find(attrs={'class':'td-post-content'}).text.replace('\n','')
  if june_title == []:
    print("Title could not be found")
    continue
  else:
    print(f"Title of the article is : {june_title} \nText of the article is : {june_text}")

  # get the domain as the file name
  domain = " ".join(june_title)
  description = june_text
  filename = response.url.replace("/",'') + '.txt'
  with open("/content/drive/MyDrive/20211030 Test Assignment/output/" + filename, 'w') as f:
      f.write(domain +'\n' + description)

  # appending all the title and text in a list
  domain = " ".join(june_title)
  description = june_text
  title_all.append(domain)
  text_all.append(description)

# adding title and text to the dataframe
june_df.insert(2,'Title', title_all)
june_df.insert(3,'Text', text_all)
june_df

"""### **July**"""

july_df = df.loc[df['month']==7]

#Function to extract Title and text from the article published in July
## create an array with URLs
urls = july_df['URL']

## initializing the UserAgent object
user_agent = UserAgent()

# defining empty list for title and text
title_all = []
text_all = []

#scrape elements
for url in urls:
  response = requests.get(url, headers={"user-agent": user_agent.chrome})
  soup = BeautifulSoup(response.content, "html.parser")

  ## Then parse the HTML, extract title and article
  july_title = soup.find(attrs={'class':'td-post-title'}).text.replace('\n','')
  july_title = (re.findall('Think(.*)July', july_title))
  july_text = soup.find(attrs={'class':'td-post-content'}).text.replace('\n','')
  if july_title == []:
    print("Title could not be found")
    continue
  else:
    print(f"Title of the article is : {july_title} \nText of the article is : {july_text}")

# get the domain as the file name
  domain = " ".join(july_title)
  description = july_text
  filename = response.url.replace("/",'') + '.txt'
  with open("/content/drive/MyDrive/20211030 Test Assignment/output/" + filename, 'w') as f:
      f.write(domain +'\n' + description)

  # appending all the title and text in a list
  domain = " ".join(july_title)
  description = july_text
  title_all.append(domain)
  text_all.append(description)

july_df

# adding title and text to the dataframe
july_df.insert(2,'Title', title_all)
july_df.insert(3,'Text', text_all)
july_df

"""### **August**"""

aug_df = df.loc[df['month']==8]

#Function to extract Title and text from the article published in August
## create an array with URLs
urls = aug_df['URL']

## initializing the UserAgent object
user_agent = UserAgent()

# defining empty list for title and text
title_all = []
text_all = []

#scrape elements
for url in urls:
  response = requests.get(url, headers={"user-agent": user_agent.chrome})
  soup = BeautifulSoup(response.content, "html.parser")

  ## Then parse the HTML, extract title and article
  aug_title = soup.find(attrs={'class':'td-post-title'}).text.replace('\n','')
  aug_title = (re.findall('Think(.*)August', aug_title))
  aug_text = soup.find(attrs={'class':'td-post-content'}).text.replace('\n','')
  if aug_title == []:
    print("Title could not be found")
    continue
  else:
    print(f"Title of the article is : {aug_title} \nText of the article is : {aug_text}")

# get the domain as the file name
  domain = " ".join(aug_title)
  description = aug_text
  filename = response.url.replace("/",'') + '.txt'
  with open("/content/drive/MyDrive/20211030 Test Assignment/output/" + filename, 'w') as f:
      f.write(domain +'\n' + description)

  # appending all the title and text in a list
  domain = " ".join(aug_title)
  description = aug_text
  title_all.append(domain)
  text_all.append(description)

# adding title and text to the dataframe
aug_df.insert(2,'Title', title_all)
aug_df.insert(3,'Text', text_all)
aug_df

"""**September**"""

sept_df = df.loc[df['month']==9]

#Function to extract Title and text from the article published in September
## create an array with URLs
urls = sept_df['URL']

## initializing the UserAgent object
user_agent = UserAgent()

# defining empty list for title and text
title_all = []
text_all = []

#scrape elements
for url in urls:
  response = requests.get(url, headers={"user-agent": user_agent.chrome})
  soup = BeautifulSoup(response.content, "html.parser")

  ## Then parse the HTML, extract title and article
  sept_title = soup.find(attrs={'class':'td-post-title'}).text.replace('\n','')
  sept_title = (re.findall('Think(.*)September', sept_title))
  sept_text = soup.find(attrs={'class':'td-post-content'}).text.replace('\n','')
  if sept_title == []:
    print("Title could not be found")
    continue
  else:
    print(f"Title of the article is : {sept_title} \nText of the article is : {sept_text}")

# get the domain as the file name
  domain = " ".join(sept_title)
  description = sept_text
  filename = response.url.replace("/",'') + '.txt'
  with open("/content/drive/MyDrive/20211030 Test Assignment/output/" + filename, 'w') as f:
      f.write(domain +'\n' + description)

  # appending all the title and text in a list
  domain = " ".join(sept_title)
  description = sept_text
  title_all.append(domain)
  text_all.append(description)

# adding title and text to the dataframe
sept_df.insert(2,'Title', title_all)
sept_df.insert(3,'Text', text_all)
sept_df

"""**October**"""

oct_df = df.loc[df['month']==10]

#Function to extract Title and text from the article published in October
## create an array with URLs
urls = oct_df['URL']

## initializing the UserAgent object
user_agent = UserAgent()

# defining empty list for title and text
title_all = []
text_all = []

#scrape elements
for url in urls:
  response = requests.get(url, headers={"user-agent": user_agent.chrome})
  soup = BeautifulSoup(response.content, "html.parser")

  ## Then parse the HTML, extract title and article
  oct_title = soup.find(attrs={'class':'td-post-title'}).text.replace('\n','')
  oct_title = (re.findall('Think(.*)October', oct_title))
  oct_text = soup.find(attrs={'class':'td-post-content'}).text.replace('\n','')
  if oct_title == []:
    print("Title could not be found")
    continue
  else:
    print(f"Title of the article is : {oct_title} \nText of the article is : {oct_text}")

# get the domain as the file name
  domain = " ".join(oct_title)
  description = oct_text
  filename = response.url.replace("/",'') + '.txt'
  with open("/content/drive/MyDrive/20211030 Test Assignment/output/" + filename, 'w') as f:
      f.write(domain +'\n' + description)

  # appending all the title and text in a list
  domain = " ".join(oct_title)
  description = oct_text
  title_all.append(domain)
  text_all.append(description)

oct_df

# adding title and text to the dataframe
oct_df.insert(2,'Title', title_all)
oct_df.insert(3,'Text', text_all)
oct_df

"""**November**"""

nov_df = df.loc[df['month']==11]

#Function to extract Title and text from the article published in November
## create an array with URLs
urls = nov_df['URL']

## initializing the UserAgent object
user_agent = UserAgent()

# defining empty list for title and text
title_all = []
text_all = []

#scrape elements
for url in urls:
  response = requests.get(url, headers={"user-agent": user_agent.chrome})
  soup = BeautifulSoup(response.content, "html.parser")

  ## Then parse the HTML, extract title and article
  nov_title = soup.find(attrs={'class':'td-post-title'}).text.replace('\n','')
  nov_title = (re.findall('Think(.*)November', nov_title))
  nov_text = soup.find(attrs={'class':'td-post-content'}).text.replace('\n','')
  if nov_title == []:
    print("Title could not be found")
    continue
  else:
    print(f"Title of the article is : {nov_title} \nText of the article is : {nov_text}")

# get the domain as the file name
  domain = " ".join(nov_title)
  description = nov_text
  filename = response.url.replace("/",'') + '.txt'
  with open("/content/drive/MyDrive/20211030 Test Assignment/output/" + filename, 'w') as f:
      f.write(domain +'\n' + description)

  # appending all the title and text in a list
  domain = " ".join(nov_title)
  description = nov_text
  title_all.append(domain)
  text_all.append(description)

nov_df

"""**We can see that Title of URL in index 95 can't be extracted. Lets find it out now.**"""

# Left over articles
urls = 'https://insights.blackcoffer.com/marketing-drives-results-with-a-focus-on-problems/'

## initializing the UserAgent object
user_agent = UserAgent()

#scrape elements
response = requests.get(urls, headers={"user-agent": user_agent.chrome})
soup = BeautifulSoup(response.content, "html.parser")

## Then parse the HTML, extract title and article
nov_title = soup.find(attrs={'class':'td-post-title'}).text.replace('\n','')
nov_title = (re.findall('Marketing(.*)November', nov_title))
nov_text = soup.find(attrs={'class':'td-post-content'}).text.replace('\n','')
nov_text = re.sub(r'http\S+', '', nov_text)

print(f"Title of the article is : {nov_title} \nText of the article is : {nov_text}")

# get the domain as the file name
domain = " ".join(nov_title)
description = nov_text
filename = response.url.replace("/",'') + '.txt'
with open("/content/drive/MyDrive/20211030 Test Assignment/output/" + filename, 'w') as f:
  f.write(domain +'\n' + description)

# appending all the title and text in a list
domain = " ".join(nov_title)
description = nov_text
title_all.append(domain)
text_all.append(description)

# rearranging dataframe
nov_df_re =nov_df.reindex([48,49,58,96,95])
nov_df_re

# adding title and text to the dataframe
nov_df_re.insert(2,'Title', title_all)
nov_df_re.insert(3,'Text', text_all)
nov_df_re

"""**December**"""

dec_df = df.loc[df['month']==12]

#Function to extract Title & Text and giving a file name from the article published in November
## create an array with URLs
urls = dec_df['URL']

## initializing the UserAgent object
user_agent = UserAgent()

# defining empty list for title and text
title_all = []
text_all = []

#scrape elements
for url in urls:
  response = requests.get(url, headers={"user-agent": user_agent.chrome})
  soup = BeautifulSoup(response.content, "html.parser")

  ## Then parse the HTML, extract title and article
  dec_title = soup.find(attrs={'class':'td-post-title'}).text.replace('\n','')
  dec_title = (re.findall('Think(.*)December', dec_title))
  dec_text = soup.find(attrs={'class':'td-post-content'}).text.replace('\n','')

  if dec_title == []:
    print("Title could not be found")
  else:
    print(f"Title of the article is : {dec_title} \nText of the article is : {dec_text}")

# get the domain as the file name
  domain = " ".join(dec_title)
  description = dec_text
  filename = response.url.replace("/",'') + '.txt'
  with open("/content/drive/MyDrive/20211030 Test Assignment/output/" + filename, 'w') as f:
      f.write(domain +'\n' + description)

  # appending all the title and text in a list
  domain = " ".join(dec_title)
  description = dec_text
  title_all.append(domain)
  text_all.append(description)

# adding title and text to the dataframe
dec_df.insert(2,'Title', title_all)
dec_df.insert(3,'Text', text_all)
dec_df

# adding all dataframes into a single dataframe
new_df = pd.concat([jan_df, feb_df, mar_df_re, apr_df_re, may_df, june_df, july_df, aug_df, sept_df, oct_df, nov_df_re, dec_df], axis=0, join='inner')

# adding title and text in one column as full text
new_df['text'] = new_df['Title'] + new_df['Text']

# dropping Title and Text column
new_df.drop(['Title','Text'], axis=1,inplace=True)

new_df

"""# **Textual Analysis**

### Text Cleaning
"""

# Removing everything except the alphabets
def clean_text(x):
    return re.sub(r"[^a-zA-Z ]"," ",str(x))

# applying above function
new_df['text'] = new_df['text'].apply(clean_text)
new_df

"""### Removing Stopwords"""

# function to extract stopwords from folder
file_list = glob.glob(os.path.join(os.getcwd(), "/content/drive/MyDrive/20211030 Test Assignment/StopWords", "*.txt"))

corpus = []

for file_path in file_list:
    with open(file_path, encoding='utf8', errors='ignore') as f_input:
      corpus.append(f_input.read())
      string = " ".join( corpus )
      new_stopwords = re.sub(r'http\S+', '', string)
      new_stopwords = new_stopwords.replace('Surnames from 1990 census > .002%.  www.census.gov.genealogy/names/dist.all.last','')
      new_stopwords = re.split(r'[|,\n]', new_stopwords)
      new_stopwords.remove(' ')

print(new_stopwords)

# function to remove stopwords
def stopwords(text):
    # removing the stop words
    text = [word for word in text.split() if word not in new_stopwords]
    # joining the list of words with space separator
    return " ".join(text)

# removing stopwords from the data
new_df['text'] = new_df['text'].apply(stopwords)
new_df

"""### Tokenization"""

# function for Tokenization
def tokenizer(txt):
  tokens = word_tokenize(txt)
  return tokens

# Applying Tokenization
new_df['text'] = new_df['text'].apply(tokenizer)
new_df

"""### Lemmatization

Lemmatization is responsible for grouping different inflected forms of words into the root form, having the same meaning.
"""

# Applying Lemmatization
def clean_text(text):
    le=WordNetLemmatizer()
    word_tokens=word_tokenize(text)
    tokens=[le.lemmatize(w) for w in word_tokens]
    cleaned_text=" ".join(tokens)
    return cleaned_text

# Function for Lemmatization
le = WordNetLemmatizer()

def stem_text(text):
  lemmatize = []
  for word in text:
    lemmatize.append(word)
  return lemmatize

# Applying Lemmatization
new_df['text'] = new_df['text'].apply(stem_text)
new_df

#join words fun
def join_words(x):
  return " ".join(set(x))

# Applying above function
new_df['text'] = new_df['text'].apply(join_words)
new_df

"""## **Creating Dictionary of Positive and Negative words**

**Positive Words**
"""

# extracting positive words from the folder
file = open("/content/drive/MyDrive/20211030 Test Assignment/MasterDictionary/positive-words.txt", "r")
pos_words = file.read().split()
print(pos_words)

"""**Negative Words**"""

file = open("/content/drive/MyDrive/20211030 Test Assignment/MasterDictionary/negative-words.txt", encoding='utf8', errors='ignore')
neg_words = file.read().split()
print(neg_words)

"""## **Extracting Derived variables**

**POSITIVE SCORE**
"""

# Finding positive scores of text
num_pos = new_df['text'].map(lambda x: len([i for i in x.split() if i in pos_words]))
new_df['pos_score'] = num_pos
new_df

"""**NEGATIVE SCORE**"""

# Finding negative scores of text
num_neg = new_df['text'].map(lambda x: len([i for i in x.split() if i in neg_words]))
new_df['neg_score'] = num_neg
new_df

"""**POLARITY SCORE**"""

# Polarity Score = (Positive Score – Negative Score)/ ((Positive Score + Negative Score) + 0.000001)
# Range is from -1 to +1
new_df['polarity_score'] = (new_df['pos_score']-new_df['neg_score'])/((new_df['pos_score']+new_df['neg_score'])+0.000001)
new_df

"""**SUBJECTIVITY SCORE**"""

# Subjectivity Score = (Positive Score + Negative Score)/ ((Total Words after cleaning) + 0.000001)
# Range is from 0 to +1
word_count = new_df['text'].apply(lambda x: len((x).split()))
new_df['subj_score'] = (new_df['pos_score']+new_df['neg_score'])/((word_count)+ 0.000001)
new_df

"""## **Analysis of Readability**

**AVERAGE SENTENCE LENGTH**
"""

# Average Sentence Length = the number of words / the number of sentences
num_sentences = word_count.count()
new_df['avg_sent_len'] = word_count/num_sentences
new_df

"""**PERCENTAGE OF COMPLEX WORDS**"""

# syllable per word = no of vowels present in each word.
vowel_per_word = new_df['text'].str.count(r'[aeiou]')

# Complex words are words in the text that contain more than two syllables.
def vowelwordcount(text):

  # initializing count variable
  count = 0
  word_count = 0

  # creating a list of vowels
  vowels = ["a", "e", "i", "o", "u"]
  for row in text:
      for i in row:
         if i in vowels:
          count += 1
      if count>2:
        word_count += 1
  return word_count

complex_words = new_df['text'].apply(vowelwordcount)

# Percentage of Complex words = the number of complex words / the number of words
# complex words = more than two vowels present in each word.
new_df['percent_complex_words'] = complex_words/word_count
new_df

"""**FOG INDEX**"""

# Fog Index = 0.4 * (Average Sentence Length + Percentage of Complex words)
new_df['fog_index'] = 0.4* (new_df['avg_sent_len'] + new_df['percent_complex_words'])
new_df.head()

"""**AVG NUMBER OF WORDS PER SENTENCE**"""

# total number of words
total_words = word_count.sum()
total_words

# Average Number of Words Per Sentence = the total number of words / the total number of sentences
new_df['avg_words_per_sen'] = total_words/num_sentences
new_df.head()

"""**COMPLEX WORD COUNT**"""

new_df['complex_words'] = complex_words
new_df.head()

"""**WORD COUNT**"""

new_df['word_count'] = word_count
new_df.head()

"""**SYLLABLE PER WORD**"""

new_df['syllable_per_word'] = vowel_per_word
new_df.head()

"""**PERSONAL PRONOUNS**"""

# Personal Pronouns = find the counts of the words - “I,” “we,” “my,” “ours,” and “us” in the text

# function to find personal pronouns in the text
def pronounwordcount(text):

  # initializing count variable
  count = 0

  # creating a list of vowels
  pronoun = ['I', 'we', 'my', 'ours', 'us']
  for row in text:
      for i in row:
         if i in pronoun:
          count += 1
  return count

new_df['personal_pronouns'] = new_df['text'].apply(pronounwordcount)
new_df.head()

"""**AVG WORD LENGTH**"""

# Average Word Length = Sum of the total number of characters in each word/Total number of words
# function to find count of characters in each word in the text
def wordcount(text):

  # initializing count variable
  count = 0

  for row in text:
      for i in row:
        count += 1

  return count

char_in_words = new_df['text'].apply(wordcount)

new_df['avg_word_len'] = char_in_words/num_sentences
new_df.head()

"""### Customizing dataframe according to Excel File"""

new_df.drop(['status','date','year','month','text',], axis=1, inplace = True)
new_df.rename(columns = {'pos_score' : 'POSITIVE SCORE', 'neg_score': 'NEGATIVE SCORE',
                         'polarity_score' : 'POLARITY SCORE', 'subj_score' : 'SUBJECTIVITY SCORE',
                         'avg_sent_len' : 'AVG SENTENCE LENGTH', 'percent_complex_words' : 'PERCENTAGE OF COMPLEX WORDS',
                         'fog_index' : 'FOG INDEX','avg_words_per_sen' : 'AVG NUMBER OF WORDS PER SENTENCE',
                         'complex_words' : 'COMPLEX WORD COUNT', 'word_count' : 'WORD COUNT', 'syllable_per_word' : 'SYLLABLE PER WORD',
                         'personal_pronouns' : 'PERSONAL PRONOUNS', 'avg_word_len' : 'AVG WORD LENGTH'}, inplace = True)

new_df

new_df.sort_values(by=['URL_ID'], axis=0, inplace=True)

new_df

"""### **Writing dataframe to Excel File**"""

new_df.to_excel('/content/drive/MyDrive/20211030 Test Assignment/Output Data Structure.xlsx', sheet_name='Sheet1',index=False)